/**
 * Glossary of PoE2 jargon. Words appearing in body text get auto-linked with
 * a hover tooltip. Keep it terse — definitions, not essays.
 *
 * Keys are lowercased + space-collapsed for matching (e.g. "hollow palm"
 * matches "Hollow Palm" and "hollow  palm"). Match prefers longer keys
 * first, so multi-word entries win over single-word substrings.
 */

export interface GlossaryEntry {
  /** The canonical display term (preserved capitalization). */
  term: string;
  /** Short definition shown in the tooltip. */
  short: string;
  /** Optional longer description. */
  long?: string;
  /** Tag for grouping in the sidebar (e.g. "stat", "mechanic", "build"). */
  tag?: string;
}

/** Hand-curated terms. Add liberally. */
export const GLOSSARY: GlossaryEntry[] = [
  // Stat terms
  { term: "Spirit", tag: "stat", short: "PoE2's reservation budget. You reserve Spirit to keep buffs / minions active. Found on amulets and through some skills." },
  { term: "EHP", tag: "stat", short: "Effective Hit Pool. The actual hit you can survive once life + mitigation + recovery layers are factored in. PoB reports it per damage type." },
  { term: "TotalEHP", tag: "stat", short: "Combined effective HP across all damage types — quick survivability summary." },
  { term: "DPS", tag: "stat", short: "Damage Per Second. PoB's TotalDPS reflects main-skill DPS; CombinedDPS adds DoT layers." },
  { term: "Combo", tag: "mechanic", short: "PoE2 combo system — combo points generated by certain skills (e.g. Killing Palm) and consumed by 'expender' skills (e.g. Tempest Bell, Whirling Assault)." },
  { term: "Runic Ward", tag: "mechanic", short: "0.5 league mechanic. A new defensive resource pool that protects you once life is depleted, fueled by Verisium / Runeforging." },
  { term: "OverCap", tag: "stat", short: "Resistance over the 75% cap. Useful against curses and penetration; doesn't help vs uncurseable hits." },

  // PoE2 keystones / build identities
  { term: "Hollow Palm", tag: "build", short: "Keystone: 'Can Attack as though using a Quarterstaff while both of your hand slots are empty.' Hits gain phys/speed/crit scaled by armour stats. The Monk Martial Artist signature." },
  { term: "Hollow Palm Technique", tag: "build", short: "See: Hollow Palm. Keystone passive for the unarmed monk archetype." },
  { term: "Martial Artist", tag: "build", short: "Monk ascendancy added in PoE2 0.5. Theme: illusory bell + mirage clones + power-charge engine + unarmed scaling." },
  { term: "Invoker", tag: "build", short: "Monk ascendancy. Elemental conversion + Combat Frenzy charge generation + heavy defensive layering." },
  { term: "Acolyte of Chayula", tag: "build", short: "Monk ascendancy. Chaos / darkness theme, energy-shield-based, squishier but unique mechanics." },
  { term: "Lineage Gem", tag: "mechanic", short: "PoE2 gem variant family that augments a base skill. Each Lineage adds a different sub-effect (e.g. Tempest Bell's Triple Buff)." },

  // Tree / passive
  { term: "Keystone", tag: "tree", short: "Major tradeoff passive — game-changing benefit usually paired with a drawback. Diamond-shaped on the tree." },
  { term: "Notable", tag: "tree", short: "Named passive with multiple stats. Pentagonal on the tree. The named clusters around the wheel." },
  { term: "Ascendancy", tag: "tree", short: "Your second specialization tree, unlocked via the Trials of Sekhema and similar. Each class has 3 ascendancies." },
  { term: "Mastery", tag: "tree", short: "Choose-one effects bound to certain notable clusters. Currently 0 in PoE2 0.4 tree — may return." },
  { term: "Jewel Socket", tag: "tree", short: "Spot on the tree where you slot a Jewel item for extra mods." },

  // Skill mechanics
  { term: "Frenzy Charge", tag: "mechanic", short: "+4% attack / cast / movement speed each. Cap is class-default 3, raisable via tree/gear." },
  { term: "Power Charge", tag: "mechanic", short: "+40% increased Crit Hit Chance per charge. Default cap 3." },
  { term: "Endurance Charge", tag: "mechanic", short: "Phys damage reduction + elemental resist per charge. Default cap 3." },
  { term: "Penetration", tag: "mechanic", short: "Ignores X% of the enemy's resistance for that damage type. Stacks with OverCap-style reductions." },
  { term: "Stun Threshold", tag: "mechanic", short: "Damage required to stun the enemy. Heavy Stun triggers extra effects in PoE2 (e.g. Concussive Runes support)." },
  { term: "Heavy Stun", tag: "mechanic", short: "Triggers when you exceed the enemy's full stun threshold in one hit. Several PoE2 supports key off this." },

  // Common stat/item terms — auto-linked in passive stats and item mods
  { term: "Life", tag: "stat", short: "Your HP pool. Maxed out by life rolls on gear + tree + flask sustain." },
  { term: "Mana", tag: "stat", short: "Skill resource. Most skills cost mana per cast/attack." },
  { term: "Energy Shield", tag: "stat", short: "ES — secondary HP layer that absorbs damage before life. Regenerates after delay if not hit." },
  { term: "Evasion", tag: "stat", short: "Chance to fully avoid attacks (not spells). Diminishing returns at high values; entropy-bound." },
  { term: "Armour", tag: "stat", short: "Reduces physical damage from hits via a logarithmic formula. Less useful against very large hits." },
  { term: "Block Chance", tag: "stat", short: "% chance to block an attack outright (no damage taken). Requires a shield or specific keystones." },
  { term: "Critical Hit", tag: "stat", short: "An amplified attack/spell hit. CritChance% rolls, then CritMultiplier% applies to the damage." },
  { term: "Attack Damage", tag: "stat", short: "Damage from attack skills (uses weapon damage as the base)." },
  { term: "Skill Speed", tag: "stat", short: "How fast skills execute — combines attack speed and cast speed depending on the skill type." },
  { term: "Resistance", tag: "stat", short: "Damage reduction for that element. Capped at 75% by default; overcap matters vs penetration." },
  { term: "Daze", tag: "mechanic", short: "PoE2-specific: short stun-like interrupt. Easier to apply than full stun; stacks with stun-related supports." },
  { term: "Shock", tag: "mechanic", short: "Lightning ailment: increases damage the target takes by up to 20% based on hit size." },
  { term: "Ignite", tag: "mechanic", short: "Fire ailment: deals damage over time based on the hit that applied it." },
  { term: "Freeze", tag: "mechanic", short: "Cold ailment: locks the target in place. Duration scales with hit damage vs ailment threshold." },

  // Build slang
  { term: "League Starter", tag: "build", short: "A build you commit to for the opening days of a new league when currency is scarce. Prioritizes self-sufficient progression." },
  { term: "Mageblood", tag: "build", short: "Iconic unique belt: 'You can have N active Magic Utility Flasks; Flasks always apply their buff while you have charges.' Endgame staple." },
  { term: "SSF", tag: "build", short: "Solo Self-Found. Trade league with trade disabled — every item must be self-acquired." },
  { term: "HCSSF", tag: "build", short: "Hardcore SSF. Death = your character is dead. The most demanding format." },
  { term: "Pinnacle Boss", tag: "build", short: "PoE2's top-tier bosses (Arbiter of Ash etc.). Different mods, mechanics, and damage scaling than mapping content." },
];

/** Sort key length descending so multi-word terms match before substrings. */
const GLOSSARY_SORTED = [...GLOSSARY].sort((a, b) => b.term.length - a.term.length);

/**
 * Build a regex that matches any glossary term (case-insensitive, word-bounded).
 * Cached.
 */
let GLOSSARY_REGEX: RegExp | null = null;
export function glossaryRegex(): RegExp {
  if (GLOSSARY_REGEX) return GLOSSARY_REGEX;
  const alt = GLOSSARY_SORTED.map((e) => escapeRegex(e.term)).join("|");
  GLOSSARY_REGEX = new RegExp(`\\b(${alt})\\b`, "gi");
  return GLOSSARY_REGEX;
}

export function lookupGlossary(term: string): GlossaryEntry | null {
  const key = term.trim().toLowerCase();
  return GLOSSARY.find((e) => e.term.toLowerCase() === key) ?? null;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
